name: makeawish
favicon: null
layout_spectrum: 0.75129
typography_spectrum: 0.85807
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#005f73'
    - '#7dd0bc'
    - '#d52d22'
    - '#7e5c61'
    - '#f7e0da'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
